version: "3"

services:
  gymfy_database:
    container_name: "gymfy-database"
    image: mysql:5.7
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: gymfy_development
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root